package com.etoak.book.books.dao.scott;

import com.etoak.book.books.po.scott.Bookpic;
import com.etoak.book.books.po.scott.BookpicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookpicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int countByExample(BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int deleteByExample(BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int insert(Bookpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int insertSelective(Bookpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    List<Bookpic> selectByExample(BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    Bookpic selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") Bookpic record, @Param("example") BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByExample(@Param("record") Bookpic record, @Param("example") BookpicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByPrimaryKeySelective(Bookpic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByPrimaryKey(Bookpic record);
}