package com.etoak.book.books.dao.scott;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.etoak.book.books.po.scott.Book;
import com.etoak.book.books.po.scott.BookExample;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    List<Book> selectByExample(BookExample example);
    List<Book> selectSome(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    Book selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    int updateByPrimaryKey(Book record);
}