package com.etoak.book.books.po.scott;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.ID
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.NAME
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private String name;

    @Override
	public String toString() {
		return "Book [id=" + id + ", name=" + name + ", price=" + price
				+ ", author=" + author + ", publishdate=" + publishdate
				+ ", status=" + status + ", categoryid=" + categoryid + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.PRICE
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private Date publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.STATUS
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    private String categoryid;
    private Category category;
    

    public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.ID
     *
     * @return the value of SCOTT.BOOK.ID
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.ID
     *
     * @param ID the value for SCOTT.BOOK.ID
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.NAME
     *
     * @return the value of SCOTT.BOOK.NAME
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.NAME
     *
     * @param NAME the value for SCOTT.BOOK.NAME
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.PRICE
     *
     * @return the value of SCOTT.BOOK.PRICE
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.PRICE
     *
     * @param PRICE the value for SCOTT.BOOK.PRICE
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.AUTHOR
     *
     * @return the value of SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.AUTHOR
     *
     * @param AUTHOR the value for SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @return the value of SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @param PUBLISHDATE the value for SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.STATUS
     *
     * @return the value of SCOTT.BOOK.STATUS
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.STATUS
     *
     * @param STATUS the value for SCOTT.BOOK.STATUS
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.CATEGORYID
     *
     * @return the value of SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.CATEGORYID
     *
     * @param CATEGORYID the value for SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Thu Nov 02 09:52:07 CST 2017
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid == null ? null : categoryid.trim();
    }
}